name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Add Google Search Console Verification Meta Tag
        run: |
          sed -i 's/<\/head>/<meta name="google-site-verification" content="fyb5NhGYCkKpFsBqGUPpth6Lmu0TH0N_ggVyl3SvZzk" \/><\/head>/' dist/index.html
          
      - name: Verify Meta Tag was Added
        run: |
          grep -o 'google-site-verification' dist/index.html || echo "WARNING: Meta tag not found!"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
